config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  mount Sidekiq::Web => '/sidekiq'

  resources :proponents do
    collection do
      get :calculate_inss
      get :report
      get :salary_report
    end

    member do
      post :update_salary
    end
  end
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :proponent

  validates :street, presence: true
  validates :number, presence: true
  validates :neighborhood, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/proponent.rb
# frozen_string_literal: true

class Proponent < ApplicationRecord
  has_one :address, dependent: :destroy

  accepts_nested_attributes_for :address

  validates :name, presence: true
  validates :cpf, presence: true, uniqueness: true
  validates :birth_date, presence: true
  validates :salary, presence: true
  validates :inss_discount, presence: true
  validates :personal_contact, presence: true
  validates :reference_contact, presence: true

  def self.salary_ranges
    {
      'Até R$ 1.045,00' => Proponent.where('salary <= ?', 1045),
      'De R$ 1.045,01 a R$ 2.089,60' => Proponent.where('salary > ? AND salary <= ?', 1045, 2089.60),
      'De R$ 2.089,61 até R$ 3.134,40' => Proponent.where('salary > ? AND salary <= ?', 2089.60, 3134.40),
      'De R$ 3.134,41 até R$ 6.101,06' => Proponent.where('salary > ? AND salary <= ?', 3134.40, 6101.06),
      'Acima de R$ 6.101,06' => Proponent.where('salary > ?', 6101.06)
    }
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/proponents_controller.rb
# frozen_string_literal: true

require 'inss_calculator'

class ProponentsController < ApplicationController
  before_action :set_proponent, only: %i[show edit update destroy]

  # GET /proponents or /proponents.json
  def index
    @proponents = Proponent.page(params[:page]).per(5)
  end

  # GET /proponents/1 or /proponents/1.json
  def show; end

  # GET /proponents/new
  def new
    @proponent = Proponent.new
    @proponent.build_address
  end

  # GET /proponents/1/edit
  def edit; end

  # POST /proponents or /proponents.json
  def create
    @proponent = Proponent.new(proponent_params)
    @proponent.inss_discount = INSSCalculator.calculate_inss_discount(@proponent.salary)

    respond_to do |format|
      if @proponent.save
        format.html { redirect_to proponent_url(@proponent), notice: 'Proponent was successfully created.' }
        format.json { render :show, status: :created, location: @proponent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proponent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proponents/1 or /proponents/1.json
  def update
    @proponent.attributes = proponent_params
    @proponent.inss_discount = INSSCalculator.calculate_inss_discount(@proponent.salary)

    respond_to do |format|
      if @proponent.save
        format.html { redirect_to proponent_url(@proponent), notice: 'Proponent was successfully updated.' }
        format.json { render :show, status: :ok, location: @proponent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proponent.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_salary
    proponent = Proponent.find(params[:id])
    new_salary = params[:salary]

    UpdateSalaryJob.perform_later(proponent.id, new_salary)

    redirect_to proponents_path, notice: 'Salary update is being processed.'
  end

  # DELETE /proponents/1 or /proponents/1.json
  def destroy
    @proponent.destroy

    respond_to do |format|
      format.html { redirect_to proponents_url, notice: 'Proponent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def calculate_inss
    salary = params[:salary].to_f
    inss_discount = INSSCalculator.calculate_inss_discount(salary)

    render json: { inss_discount: }
  end

  def report
    @salary_ranges = Proponent.salary_ranges
  end

  def salary_report
    data = Proponent.salary_ranges.transform_values(&:count)

    render json: data
  end

  private

  def set_proponent
    @proponent = Proponent.find(params[:id])
  end

  def proponent_params
    params.require(:proponent).permit(:name, :cpf, :birth_date, :salary, :personal_contact, :reference_contact,
                                      address_attributes: %i[id street number neighborhood city state zip_code _destroy])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/proponents_helper.rb
# frozen_string_literal: true

module ProponentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InssDiscount</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="folha de estilo" href=" https://cdn.jsdelivr.net/npm/chart.js@2.9.1/dist/Chart.min.css ">
    <script src=" https://cdn.jsdelivr.net/npm/chart.js@2.9.1/dist/Chart.min.js "></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/proponents/_form.html.erb
<%= form_with(model: proponent) do |form| %>
  <% if proponent.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(proponent.errors.count, "error") %> prohibited this proponent from being saved:</h2>

      <ul>
        <% proponent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :birth_date, style: "display: block" %>
    <%= form.date_field :birth_date %>
  </div>

  <div>
    <%= form.label :salary, style: "display: block" %>
    <%= form.text_field :salary %>
  </div>

  <div>
    <%= form.label :inss_discount, style: "display: block" %>
    <%= form.text_field :inss_discount, id: 'inss_discount', readonly: true %>
  </div>

  <div>
    <%= form.label :personal_contact, style: "display: block" %>
    <%= form.text_field :personal_contact %>
  </div>

  <div>
    <%= form.label :reference_contact, style: "display: block" %>
    <%= form.text_field :reference_contact %>
  </div>

  <h3>Address</h3>
  <%= form.fields_for :address do |address_form| %>
    <div>
      <%= address_form.label :street %>
      <%= address_form.text_field :street %>
    </div>

    <div>
      <%= address_form.label :number %>
      <%= address_form.text_field :number %>
    </div>

    <div>
      <%= address_form.label :neighborhood %>
      <%= address_form.text_field :neighborhood %>
    </div>

    <div>
      <%= address_form.label :city %>
      <%= address_form.text_field :city %>
    </div>

    <div>
      <%= address_form.label :state %>
      <%= address_form.text_field :state %>
    </div>

    <div>
      <%= address_form.label :zip_code %>
      <%= address_form.text_field :zip_code %>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<script>
window.onload = () => {
  const salaryField = document.getElementById('proponent_salary');
  const inssDiscountField = document.getElementById('inss_discount');

  salaryField.addEventListener('change', () => {
    const salary = salaryField.value;

    if (salary) {
      fetch(`/proponents/calculate_inss?salary=${salary}`)
        .then(response => response.json())
        .then(data => {
          inssDiscountField.value = data.inss_discount.toFixed(2);
        })
        .catch(error => {
          console.error('Error:', error);
        });
    } else {
      inssDiscountField.value = '0.00';
    }
  });
};
</script>

app/views/proponents/_proponent.html.erb
<div id="<%= dom_id @proponent %>">
  <p>
    <strong>Name:</strong>
    <%= @proponent.name %>
  </p>

  <p>
    <strong>CPF:</strong>
    <%= @proponent.cpf %>
  </p>

  <p>
    <strong>Birth date:</strong>
    <%= @proponent.birth_date %>
  </p>

  <p>
    <strong>Salary:</strong>
    <%= @proponent.salary %>
  </p>

  <p>
    <strong>INSS disount:</strong>
    <%= @proponent.inss_discount %>
  </p>

  <p>
    <strong>Personal contact:</strong>
    <%= @proponent.personal_contact %>
  </p>

  <p>
    <strong>Reference contact:</strong>
    <%= @proponent.reference_contact %>
  </p>

  <% if @proponent.address.present? %>
    <h3>Address</h3>
    <p>
      <strong>Street:</strong>
      <%= @proponent.address.street %>
    </p>

    <p>
      <strong>Number:</strong>
      <%= @proponent.address.number %>
    </p>

    <p>
      <strong>Neighborhood:</strong>
      <%= @proponent.address.neighborhood %>
    </p>

    <p>
      <strong>City:</strong>
      <%= @proponent.address.city %>
    </p>

    <p>
      <strong>State:</strong>
      <%= @proponent.address.state %>
    </p>

    <p>
      <strong>Zip Code:</strong>
      <%= @proponent.address.zip_code %>
    </p>
  <% else %>
    <p>No address available</p>
  <% end %>
</div>

app/views/proponents/edit.html.erb
<h1>Editing proponent</h1>

<%= render "form", proponent: @proponent %>

<br>

<div>
  <%= link_to "Show this proponent", @proponent %> |
  <%= link_to "Back to proponents", proponents_path %>
</div>

app/views/proponents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Proponents</h1>

<%= link_to "New proponent", new_proponent_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>CPF</th>
      <th>Salary</th>
      <th></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @proponents.each do |proponent| %>
      <tr>
        <td><%= proponent.name %></td>
        <td><%= proponent.cpf %></td>
        <td><%= number_to_currency(proponent.salary) %></td>
        <td>
          <%= form_with url: update_salary_proponent_path(proponent), method: :post do %>
            <%= text_field_tag :salary, nil, placeholder: "Novo Salário" %>
            <%= submit_tag 'Atualizar Salário' %>
          <% end %>
        </td>
        <td>
          <%= link_to "Show", proponent %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pagination">
  <%= paginate @proponents %> <!-- Paginação -->
</div>

app/views/proponents/new.html.erb
<h1>New proponent</h1>

<%= render "form", proponent: @proponent %>

<br>

<div>
  <%= link_to "Back to proponents", proponents_path %>
</div>

app/views/proponents/report.html.erb
<h1>Relatório de Funcionários</h1>

<h2>Funcionários por Faixa Salarial</h2>
<% @salary_ranges.each do |range, proponents| %>
  <h3><%= range %> (Total: <%= proponents.count %>)</h3>
  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>CPF</th>
        <th>Salário</th>
      </tr>
    </thead>
    <tbody>
      <% proponents.each do |proponent| %>
        <tr>
          <td><%= proponent.name %></td>
          <td><%= proponent.cpf %></td>
          <td><%= number_to_currency(proponent.salary) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<canvas id="myChart" width="960" height="200"></canvas>

<script>
window.onload = () => {
  fetch('/proponents/salary_report')
    .then(response => response.json())
    .then(data => {
      const salaryLabels = Object.keys(data);
      const salaryData = Object.values(data);

      const ctx = document.getElementById('myChart');
      const myChart = new Chart(ctx, {
        type: 'bar',
        data: {
          labels: salaryLabels,
          datasets: [{
            label: 'Funcionários por Faixa Salarial',
            data: salaryData,
            backgroundColor: ['rgba(255, 206, 86, 0.2)', 'rgba(75, 192, 192, 0.2)', 'rgba(153, 102, 255, 0.2)', 'rgba(255, 159, 64, 0.2)'],
            borderColor: ['rgba(255, 206, 86, 1)', 'rgba(75, 192, 192, 1)', 'rgba(153, 102, 255, 1)', 'rgba(255, 159, 64, 1)'],
            borderWidth: 1
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: true
              }
            }]
          }
        }
      });
    })
    .catch(error => {
        console.error('Error:', error);
    });
};
</script>

app/views/proponents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @proponent %>

<div>
  <%= link_to "Edit this proponent", edit_proponent_path(@proponent) %> |
  <%= link_to "Back to proponents", proponents_path %>

  <%= button_to "Destroy this proponent", @proponent, method: :delete %>
</div>